const mock=// 20220531101117
// http://localhost:4000/forecast/spain

{
  "location": {
    "name": "Madrid",
    "region": "Madrid",
    "country": "Spain",
    "lat": 40.4,
    "lon": -3.68,
    "tz_id": "Europe/Madrid",
    "localtime_epoch": 1653984526,
    "localtime": "2022-05-31 10:08"
  },
  "current": {
    "last_updated_epoch": 1653980400,
    "last_updated": "2022-05-31 09:00",
    "temp_c": 18,
    "temp_f": 64.4,
    "is_day": 1,
    "condition": {
      "text": "Sunny",
      "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
      "code": 1000,
      "condition_spanishDayText": "Soleado",
      "condition_spanishNightText": "Despejado"
    },
    "wind_mph": 2.2,
    "wind_kph": 3.6,
    "wind_degree": 84,
    "wind_dir": "E",
    "pressure_mb": 1015,
    "pressure_in": 29.97,
    "precip_mm": 0,
    "precip_in": 0,
    "humidity": 56,
    "cloud": 0,
    "feelslike_c": 18,
    "feelslike_f": 64.4,
    "vis_km": 10,
    "vis_miles": 6,
    "uv": 5,
    "gust_mph": 2.2,
    "gust_kph": 3.6
  },
  "forecast": {
    "forecastday": [
      {
        "date": "2022-05-31",
        "date_epoch": 1653955200,
        "day": {
          "maxtemp_c": 31.7,
          "maxtemp_f": 89.1,
          "mintemp_c": 15.5,
          "mintemp_f": 59.9,
          "avgtemp_c": 23,
          "avgtemp_f": 73.4,
          "maxwind_mph": 12.8,
          "maxwind_kph": 20.5,
          "totalprecip_mm": 0,
          "totalprecip_in": 0,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 37,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
          },
          "uv": 9
        },
        "astro": {
          "sunrise": "06:48 AM",
          "sunset": "09:39 PM",
          "moonrise": "07:13 AM",
          "moonset": "10:56 PM",
          "moon_phase": "New Moon",
          "moon_illumination": "0"
        },
        "hour": [
          {
            "time_epoch": 1653948000,
            "time": "2022-05-31 00:00",
            "temp_c": 18.2,
            "temp_f": 64.8,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 242,
            "wind_dir": "WSW",
            "pressure_mb": 1012,
            "pressure_in": 29.89,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 48,
            "cloud": 13,
            "feelslike_c": 18.2,
            "feelslike_f": 64.8,
            "windchill_c": 18.2,
            "windchill_f": 64.8,
            "heatindex_c": 18.2,
            "heatindex_f": 64.8,
            "dewpoint_c": 7,
            "dewpoint_f": 44.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11,
            "gust_kph": 17.6,
            "uv": 1
          },
          {
            "time_epoch": 1653951600,
            "time": "2022-05-31 01:00",
            "temp_c": 17.9,
            "temp_f": 64.2,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 5.8,
            "wind_kph": 9.4,
            "wind_degree": 238,
            "wind_dir": "WSW",
            "pressure_mb": 1012,
            "pressure_in": 29.88,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 49,
            "cloud": 9,
            "feelslike_c": 17.9,
            "feelslike_f": 64.2,
            "windchill_c": 17.9,
            "windchill_f": 64.2,
            "heatindex_c": 17.9,
            "heatindex_f": 64.2,
            "dewpoint_c": 7,
            "dewpoint_f": 44.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.8,
            "gust_kph": 15.8,
            "uv": 1
          },
          {
            "time_epoch": 1653955200,
            "time": "2022-05-31 02:00",
            "temp_c": 17.3,
            "temp_f": 63.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.5,
            "wind_kph": 7.2,
            "wind_degree": 246,
            "wind_dir": "WSW",
            "pressure_mb": 1012,
            "pressure_in": 29.88,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 50,
            "cloud": 8,
            "feelslike_c": 17.3,
            "feelslike_f": 63.1,
            "windchill_c": 17.3,
            "windchill_f": 63.1,
            "heatindex_c": 17.3,
            "heatindex_f": 63.1,
            "dewpoint_c": 6.9,
            "dewpoint_f": 44.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.8,
            "gust_kph": 12.6,
            "uv": 1
          },
          {
            "time_epoch": 1653958800,
            "time": "2022-05-31 03:00",
            "temp_c": 16.8,
            "temp_f": 62.2,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 238,
            "wind_dir": "WSW",
            "pressure_mb": 1012,
            "pressure_in": 29.89,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 52,
            "cloud": 8,
            "feelslike_c": 16.8,
            "feelslike_f": 62.2,
            "windchill_c": 16.8,
            "windchill_f": 62.2,
            "heatindex_c": 16.8,
            "heatindex_f": 62.2,
            "dewpoint_c": 6.8,
            "dewpoint_f": 44.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6,
            "gust_kph": 9.7,
            "uv": 1
          },
          {
            "time_epoch": 1653962400,
            "time": "2022-05-31 04:00",
            "temp_c": 16.4,
            "temp_f": 61.5,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 1.8,
            "wind_kph": 2.9,
            "wind_degree": 249,
            "wind_dir": "WSW",
            "pressure_mb": 1012,
            "pressure_in": 29.9,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 53,
            "cloud": 6,
            "feelslike_c": 16.4,
            "feelslike_f": 61.5,
            "windchill_c": 16.4,
            "windchill_f": 61.5,
            "heatindex_c": 16.4,
            "heatindex_f": 61.5,
            "dewpoint_c": 6.8,
            "dewpoint_f": 44.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.1,
            "gust_kph": 5,
            "uv": 1
          },
          {
            "time_epoch": 1653966000,
            "time": "2022-05-31 05:00",
            "temp_c": 15.9,
            "temp_f": 60.6,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 0.4,
            "wind_kph": 0.7,
            "wind_degree": 260,
            "wind_dir": "W",
            "pressure_mb": 1013,
            "pressure_in": 29.9,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 55,
            "cloud": 6,
            "feelslike_c": 15.9,
            "feelslike_f": 60.6,
            "windchill_c": 15.9,
            "windchill_f": 60.6,
            "heatindex_c": 15.9,
            "heatindex_f": 60.6,
            "dewpoint_c": 6.8,
            "dewpoint_f": 44.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 0.9,
            "gust_kph": 1.4,
            "uv": 1
          },
          {
            "time_epoch": 1653969600,
            "time": "2022-05-31 06:00",
            "temp_c": 15.5,
            "temp_f": 59.9,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 1.1,
            "wind_kph": 1.8,
            "wind_degree": 90,
            "wind_dir": "E",
            "pressure_mb": 1013,
            "pressure_in": 29.92,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 57,
            "cloud": 7,
            "feelslike_c": 15.5,
            "feelslike_f": 59.9,
            "windchill_c": 15.5,
            "windchill_f": 59.9,
            "heatindex_c": 15.5,
            "heatindex_f": 59.9,
            "dewpoint_c": 7,
            "dewpoint_f": 44.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 2,
            "gust_kph": 3.2,
            "uv": 1
          },
          {
            "time_epoch": 1653973200,
            "time": "2022-05-31 07:00",
            "temp_c": 16.6,
            "temp_f": 61.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.5,
            "wind_kph": 4,
            "wind_degree": 79,
            "wind_dir": "E",
            "pressure_mb": 1014,
            "pressure_in": 29.93,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 54,
            "cloud": 8,
            "feelslike_c": 16.6,
            "feelslike_f": 61.9,
            "windchill_c": 16.6,
            "windchill_f": 61.9,
            "heatindex_c": 16.6,
            "heatindex_f": 61.9,
            "dewpoint_c": 7.3,
            "dewpoint_f": 45.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.6,
            "gust_kph": 5.8,
            "uv": 5
          },
          {
            "time_epoch": 1653976800,
            "time": "2022-05-31 08:00",
            "temp_c": 17.9,
            "temp_f": 64.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 1.8,
            "wind_kph": 2.9,
            "wind_degree": 84,
            "wind_dir": "E",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 49,
            "cloud": 8,
            "feelslike_c": 17.9,
            "feelslike_f": 64.2,
            "windchill_c": 17.9,
            "windchill_f": 64.2,
            "heatindex_c": 17.9,
            "heatindex_f": 64.2,
            "dewpoint_c": 7.1,
            "dewpoint_f": 44.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 2.2,
            "gust_kph": 3.6,
            "uv": 5
          },
          {
            "time_epoch": 1653980400,
            "time": "2022-05-31 09:00",
            "temp_c": 19.5,
            "temp_f": 67.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2,
            "wind_kph": 3.2,
            "wind_degree": 112,
            "wind_dir": "ESE",
            "pressure_mb": 1014,
            "pressure_in": 29.96,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 45,
            "cloud": 8,
            "feelslike_c": 19.5,
            "feelslike_f": 67.1,
            "windchill_c": 19.5,
            "windchill_f": 67.1,
            "heatindex_c": 19.5,
            "heatindex_f": 67.1,
            "dewpoint_c": 7.2,
            "dewpoint_f": 45,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 2.2,
            "gust_kph": 3.6,
            "uv": 5
          },
          {
            "time_epoch": 1653984000,
            "time": "2022-05-31 10:00",
            "temp_c": 21.2,
            "temp_f": 70.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.2,
            "wind_kph": 3.6,
            "wind_degree": 153,
            "wind_dir": "SSE",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 40,
            "cloud": 7,
            "feelslike_c": 21.2,
            "feelslike_f": 70.2,
            "windchill_c": 21.2,
            "windchill_f": 70.2,
            "heatindex_c": 23.9,
            "heatindex_f": 75,
            "dewpoint_c": 7.2,
            "dewpoint_f": 45,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 2.5,
            "gust_kph": 4,
            "uv": 6
          },
          {
            "time_epoch": 1653987600,
            "time": "2022-05-31 11:00",
            "temp_c": 24.1,
            "temp_f": 75.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.9,
            "wind_kph": 4.7,
            "wind_degree": 180,
            "wind_dir": "S",
            "pressure_mb": 1014,
            "pressure_in": 29.94,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 36,
            "cloud": 5,
            "feelslike_c": 24.6,
            "feelslike_f": 76.3,
            "windchill_c": 24.1,
            "windchill_f": 75.4,
            "heatindex_c": 24.6,
            "heatindex_f": 76.3,
            "dewpoint_c": 8.2,
            "dewpoint_f": 46.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.4,
            "gust_kph": 5.4,
            "uv": 6
          },
          {
            "time_epoch": 1653991200,
            "time": "2022-05-31 12:00",
            "temp_c": 25.4,
            "temp_f": 77.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 189,
            "wind_dir": "S",
            "pressure_mb": 1013,
            "pressure_in": 29.93,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 33,
            "cloud": 8,
            "feelslike_c": 25.1,
            "feelslike_f": 77.2,
            "windchill_c": 25.4,
            "windchill_f": 77.7,
            "heatindex_c": 25.1,
            "heatindex_f": 77.2,
            "dewpoint_c": 7.8,
            "dewpoint_f": 46,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4.9,
            "gust_kph": 7.9,
            "uv": 7
          },
          {
            "time_epoch": 1653994800,
            "time": "2022-05-31 13:00",
            "temp_c": 28.7,
            "temp_f": 83.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 199,
            "wind_dir": "SSW",
            "pressure_mb": 1013,
            "pressure_in": 29.91,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 29,
            "cloud": 5,
            "feelslike_c": 27.5,
            "feelslike_f": 81.5,
            "windchill_c": 28.7,
            "windchill_f": 83.7,
            "heatindex_c": 27.5,
            "heatindex_f": 81.5,
            "dewpoint_c": 8.9,
            "dewpoint_f": 48,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.4,
            "gust_kph": 11.9,
            "uv": 7
          },
          {
            "time_epoch": 1653998400,
            "time": "2022-05-31 14:00",
            "temp_c": 29.8,
            "temp_f": 85.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 7.8,
            "wind_kph": 12.6,
            "wind_degree": 207,
            "wind_dir": "SSW",
            "pressure_mb": 1012,
            "pressure_in": 29.89,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 26,
            "cloud": 4,
            "feelslike_c": 28.3,
            "feelslike_f": 82.9,
            "windchill_c": 29.8,
            "windchill_f": 85.6,
            "heatindex_c": 28.3,
            "heatindex_f": 82.9,
            "dewpoint_c": 8.4,
            "dewpoint_f": 47.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.9,
            "gust_kph": 14.4,
            "uv": 7
          },
          {
            "time_epoch": 1654002000,
            "time": "2022-05-31 15:00",
            "temp_c": 30.6,
            "temp_f": 87.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 7.6,
            "wind_kph": 12.2,
            "wind_degree": 214,
            "wind_dir": "SW",
            "pressure_mb": 1011,
            "pressure_in": 29.87,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 24,
            "cloud": 6,
            "feelslike_c": 28.9,
            "feelslike_f": 84,
            "windchill_c": 30.6,
            "windchill_f": 87.1,
            "heatindex_c": 28.9,
            "heatindex_f": 84,
            "dewpoint_c": 8,
            "dewpoint_f": 46.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.7,
            "gust_kph": 14,
            "uv": 8
          },
          {
            "time_epoch": 1654005600,
            "time": "2022-05-31 16:00",
            "temp_c": 29.2,
            "temp_f": 84.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 7.2,
            "wind_kph": 11.5,
            "wind_degree": 223,
            "wind_dir": "SW",
            "pressure_mb": 1011,
            "pressure_in": 29.85,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 23,
            "cloud": 17,
            "feelslike_c": 27.3,
            "feelslike_f": 81.1,
            "windchill_c": 29.2,
            "windchill_f": 84.6,
            "heatindex_c": 27.3,
            "heatindex_f": 81.1,
            "dewpoint_c": 5.7,
            "dewpoint_f": 42.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.3,
            "gust_kph": 13.3,
            "uv": 7
          },
          {
            "time_epoch": 1654009200,
            "time": "2022-05-31 17:00",
            "temp_c": 31.7,
            "temp_f": 89.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.3,
            "wind_kph": 13.3,
            "wind_degree": 221,
            "wind_dir": "SW",
            "pressure_mb": 1010,
            "pressure_in": 29.83,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 21,
            "cloud": 10,
            "feelslike_c": 29.5,
            "feelslike_f": 85.1,
            "windchill_c": 31.7,
            "windchill_f": 89.1,
            "heatindex_c": 29.5,
            "heatindex_f": 85.1,
            "dewpoint_c": 6.4,
            "dewpoint_f": 43.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.6,
            "gust_kph": 15.5,
            "uv": 8
          },
          {
            "time_epoch": 1654012800,
            "time": "2022-05-31 18:00",
            "temp_c": 29.5,
            "temp_f": 85.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 11,
            "wind_kph": 17.6,
            "wind_degree": 225,
            "wind_dir": "SW",
            "pressure_mb": 1010,
            "pressure_in": 29.82,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 19,
            "cloud": 7,
            "feelslike_c": 27.3,
            "feelslike_f": 81.1,
            "windchill_c": 29.5,
            "windchill_f": 85.1,
            "heatindex_c": 27.3,
            "heatindex_f": 81.1,
            "dewpoint_c": 3.4,
            "dewpoint_f": 38.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.5,
            "gust_kph": 20.2,
            "uv": 7
          },
          {
            "time_epoch": 1654016400,
            "time": "2022-05-31 19:00",
            "temp_c": 29.6,
            "temp_f": 85.3,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 12.8,
            "wind_kph": 20.5,
            "wind_degree": 231,
            "wind_dir": "SW",
            "pressure_mb": 1010,
            "pressure_in": 29.83,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 19,
            "cloud": 6,
            "feelslike_c": 27.4,
            "feelslike_f": 81.3,
            "windchill_c": 29.6,
            "windchill_f": 85.3,
            "heatindex_c": 27.4,
            "heatindex_f": 81.3,
            "dewpoint_c": 3.8,
            "dewpoint_f": 38.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.8,
            "gust_kph": 23.8,
            "uv": 7
          },
          {
            "time_epoch": 1654020000,
            "time": "2022-05-31 20:00",
            "temp_c": 27,
            "temp_f": 80.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 9.8,
            "wind_kph": 15.8,
            "wind_degree": 250,
            "wind_dir": "WSW",
            "pressure_mb": 1011,
            "pressure_in": 29.85,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 23,
            "cloud": 5,
            "feelslike_c": 25.5,
            "feelslike_f": 77.9,
            "windchill_c": 27,
            "windchill_f": 80.6,
            "heatindex_c": 25.5,
            "heatindex_f": 77.9,
            "dewpoint_c": 4.1,
            "dewpoint_f": 39.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15.2,
            "gust_kph": 24.5,
            "uv": 7
          },
          {
            "time_epoch": 1654023600,
            "time": "2022-05-31 21:00",
            "temp_c": 25.3,
            "temp_f": 77.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 6,
            "wind_kph": 9.7,
            "wind_degree": 247,
            "wind_dir": "WSW",
            "pressure_mb": 1011,
            "pressure_in": 29.86,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 25,
            "cloud": 4,
            "feelslike_c": 24.5,
            "feelslike_f": 76.1,
            "windchill_c": 25.3,
            "windchill_f": 77.5,
            "heatindex_c": 24.5,
            "heatindex_f": 76.1,
            "dewpoint_c": 3.8,
            "dewpoint_f": 38.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.2,
            "gust_kph": 18,
            "uv": 7
          },
          {
            "time_epoch": 1654027200,
            "time": "2022-05-31 22:00",
            "temp_c": 24.4,
            "temp_f": 75.9,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 212,
            "wind_dir": "SSW",
            "pressure_mb": 1012,
            "pressure_in": 29.89,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 25,
            "cloud": 3,
            "feelslike_c": 23.9,
            "feelslike_f": 75,
            "windchill_c": 24.4,
            "windchill_f": 75.9,
            "heatindex_c": 23.9,
            "heatindex_f": 75,
            "dewpoint_c": 3.1,
            "dewpoint_f": 37.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13,
            "gust_kph": 20.9,
            "uv": 1
          },
          {
            "time_epoch": 1654030800,
            "time": "2022-05-31 23:00",
            "temp_c": 23.3,
            "temp_f": 73.9,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 10.1,
            "wind_kph": 16.2,
            "wind_degree": 221,
            "wind_dir": "SW",
            "pressure_mb": 1012,
            "pressure_in": 29.9,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 26,
            "cloud": 2,
            "feelslike_c": 23.4,
            "feelslike_f": 74.1,
            "windchill_c": 23.3,
            "windchill_f": 73.9,
            "heatindex_c": 23.4,
            "heatindex_f": 74.1,
            "dewpoint_c": 2.6,
            "dewpoint_f": 36.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 19.2,
            "gust_kph": 31,
            "uv": 1
          }
        ]
      },
      {
        "date": "2022-06-01",
        "date_epoch": 1654041600,
        "day": {
          "maxtemp_c": 31.7,
          "maxtemp_f": 89.1,
          "mintemp_c": 17.4,
          "mintemp_f": 63.3,
          "avgtemp_c": 23.9,
          "avgtemp_f": 75,
          "maxwind_mph": 15.2,
          "maxwind_kph": 24.5,
          "totalprecip_mm": 0,
          "totalprecip_in": 0,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 31,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
          },
          "uv": 9
        },
        "astro": {
          "sunrise": "06:47 AM",
          "sunset": "09:39 PM",
          "moonrise": "07:56 AM",
          "moonset": "11:51 PM",
          "moon_phase": "Waxing Crescent",
          "moon_illumination": "9"
        },
        "hour": [
          {
            "time_epoch": 1654034400,
            "time": "2022-06-01 00:00",
            "temp_c": 22.4,
            "temp_f": 72.3,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 12.1,
            "wind_kph": 19.4,
            "wind_degree": 228,
            "wind_dir": "SW",
            "pressure_mb": 1013,
            "pressure_in": 29.91,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 28,
            "cloud": 0,
            "feelslike_c": 23.2,
            "feelslike_f": 73.8,
            "windchill_c": 22.4,
            "windchill_f": 72.3,
            "heatindex_c": 23.2,
            "heatindex_f": 73.8,
            "dewpoint_c": 3,
            "dewpoint_f": 37.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 22.4,
            "gust_kph": 36,
            "uv": 1
          },
          {
            "time_epoch": 1654038000,
            "time": "2022-06-01 01:00",
            "temp_c": 21.4,
            "temp_f": 70.5,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 11.9,
            "wind_kph": 19.1,
            "wind_degree": 235,
            "wind_dir": "SW",
            "pressure_mb": 1013,
            "pressure_in": 29.91,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 29,
            "cloud": 0,
            "feelslike_c": 21.4,
            "feelslike_f": 70.5,
            "windchill_c": 21.4,
            "windchill_f": 70.5,
            "heatindex_c": 23,
            "heatindex_f": 73.4,
            "dewpoint_c": 2.7,
            "dewpoint_f": 36.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 21.5,
            "gust_kph": 34.6,
            "uv": 1
          },
          {
            "time_epoch": 1654041600,
            "time": "2022-06-01 02:00",
            "temp_c": 20.3,
            "temp_f": 68.5,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 8.5,
            "wind_kph": 13.7,
            "wind_degree": 234,
            "wind_dir": "SW",
            "pressure_mb": 1013,
            "pressure_in": 29.92,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 32,
            "cloud": 2,
            "feelslike_c": 20.3,
            "feelslike_f": 68.5,
            "windchill_c": 20.3,
            "windchill_f": 68.5,
            "heatindex_c": 20.3,
            "heatindex_f": 68.5,
            "dewpoint_c": 2.9,
            "dewpoint_f": 37.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.1,
            "gust_kph": 25.9,
            "uv": 1
          },
          {
            "time_epoch": 1654045200,
            "time": "2022-06-01 03:00",
            "temp_c": 19.5,
            "temp_f": 67.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 6.9,
            "wind_kph": 11.2,
            "wind_degree": 221,
            "wind_dir": "SW",
            "pressure_mb": 1013,
            "pressure_in": 29.92,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 33,
            "cloud": 2,
            "feelslike_c": 19.5,
            "feelslike_f": 67.1,
            "windchill_c": 19.5,
            "windchill_f": 67.1,
            "heatindex_c": 19.5,
            "heatindex_f": 67.1,
            "dewpoint_c": 3,
            "dewpoint_f": 37.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13,
            "gust_kph": 20.9,
            "uv": 1
          },
          {
            "time_epoch": 1654048800,
            "time": "2022-06-01 04:00",
            "temp_c": 18.8,
            "temp_f": 65.8,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 221,
            "wind_dir": "SW",
            "pressure_mb": 1014,
            "pressure_in": 29.93,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 35,
            "cloud": 4,
            "feelslike_c": 18.8,
            "feelslike_f": 65.8,
            "windchill_c": 18.8,
            "windchill_f": 65.8,
            "heatindex_c": 18.8,
            "heatindex_f": 65.8,
            "dewpoint_c": 3.2,
            "dewpoint_f": 37.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.9,
            "gust_kph": 19.1,
            "uv": 1
          },
          {
            "time_epoch": 1654052400,
            "time": "2022-06-01 05:00",
            "temp_c": 18.1,
            "temp_f": 64.6,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 6.9,
            "wind_kph": 11.2,
            "wind_degree": 225,
            "wind_dir": "SW",
            "pressure_mb": 1014,
            "pressure_in": 29.94,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 38,
            "cloud": 4,
            "feelslike_c": 18.1,
            "feelslike_f": 64.6,
            "windchill_c": 18.1,
            "windchill_f": 64.6,
            "heatindex_c": 18.1,
            "heatindex_f": 64.6,
            "dewpoint_c": 3.7,
            "dewpoint_f": 38.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.5,
            "gust_kph": 20.2,
            "uv": 1
          },
          {
            "time_epoch": 1654056000,
            "time": "2022-06-01 06:00",
            "temp_c": 17.4,
            "temp_f": 63.3,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 227,
            "wind_dir": "SW",
            "pressure_mb": 1015,
            "pressure_in": 29.96,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 43,
            "cloud": 4,
            "feelslike_c": 17.4,
            "feelslike_f": 63.3,
            "windchill_c": 17.4,
            "windchill_f": 63.3,
            "heatindex_c": 17.4,
            "heatindex_f": 63.3,
            "dewpoint_c": 4.6,
            "dewpoint_f": 40.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.6,
            "gust_kph": 18.7,
            "uv": 1
          },
          {
            "time_epoch": 1654059600,
            "time": "2022-06-01 07:00",
            "temp_c": 17.9,
            "temp_f": 64.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 6,
            "wind_kph": 9.7,
            "wind_degree": 223,
            "wind_dir": "SW",
            "pressure_mb": 1015,
            "pressure_in": 29.98,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 45,
            "cloud": 4,
            "feelslike_c": 17.9,
            "feelslike_f": 64.2,
            "windchill_c": 17.9,
            "windchill_f": 64.2,
            "heatindex_c": 17.9,
            "heatindex_f": 64.2,
            "dewpoint_c": 5.8,
            "dewpoint_f": 42.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.2,
            "gust_kph": 14.8,
            "uv": 5
          },
          {
            "time_epoch": 1654063200,
            "time": "2022-06-01 08:00",
            "temp_c": 19.3,
            "temp_f": 66.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 6.9,
            "wind_kph": 11.2,
            "wind_degree": 222,
            "wind_dir": "SW",
            "pressure_mb": 1015,
            "pressure_in": 29.98,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 44,
            "cloud": 4,
            "feelslike_c": 19.3,
            "feelslike_f": 66.7,
            "windchill_c": 19.3,
            "windchill_f": 66.7,
            "heatindex_c": 19.3,
            "heatindex_f": 66.7,
            "dewpoint_c": 6.8,
            "dewpoint_f": 44.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.5,
            "gust_kph": 13.7,
            "uv": 5
          },
          {
            "time_epoch": 1654066800,
            "time": "2022-06-01 09:00",
            "temp_c": 20.9,
            "temp_f": 69.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.1,
            "wind_kph": 13,
            "wind_degree": 217,
            "wind_dir": "SW",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 42,
            "cloud": 2,
            "feelslike_c": 20.9,
            "feelslike_f": 69.6,
            "windchill_c": 20.9,
            "windchill_f": 69.6,
            "heatindex_c": 20.9,
            "heatindex_f": 69.6,
            "dewpoint_c": 7.4,
            "dewpoint_f": 45.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.2,
            "gust_kph": 14.8,
            "uv": 6
          },
          {
            "time_epoch": 1654070400,
            "time": "2022-06-01 10:00",
            "temp_c": 22.4,
            "temp_f": 72.3,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 9.4,
            "wind_kph": 15.1,
            "wind_degree": 210,
            "wind_dir": "SSW",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 34,
            "cloud": 2,
            "feelslike_c": 23.8,
            "feelslike_f": 74.8,
            "windchill_c": 22.4,
            "windchill_f": 72.3,
            "heatindex_c": 23.8,
            "heatindex_f": 74.8,
            "dewpoint_c": 5.8,
            "dewpoint_f": 42.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.7,
            "gust_kph": 17.3,
            "uv": 6
          },
          {
            "time_epoch": 1654074000,
            "time": "2022-06-01 11:00",
            "temp_c": 24.1,
            "temp_f": 75.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 11.4,
            "wind_kph": 18.4,
            "wind_degree": 215,
            "wind_dir": "SW",
            "pressure_mb": 1016,
            "pressure_in": 30,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 28,
            "cloud": 2,
            "feelslike_c": 24,
            "feelslike_f": 75.2,
            "windchill_c": 24.1,
            "windchill_f": 75.4,
            "heatindex_c": 24,
            "heatindex_f": 75.2,
            "dewpoint_c": 4.5,
            "dewpoint_f": 40.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.2,
            "gust_kph": 21.2,
            "uv": 6
          },
          {
            "time_epoch": 1654077600,
            "time": "2022-06-01 12:00",
            "temp_c": 25.3,
            "temp_f": 77.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 12.3,
            "wind_kph": 19.8,
            "wind_degree": 219,
            "wind_dir": "SW",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 25,
            "cloud": 3,
            "feelslike_c": 24.5,
            "feelslike_f": 76.1,
            "windchill_c": 25.3,
            "windchill_f": 77.5,
            "heatindex_c": 24.5,
            "heatindex_f": 76.1,
            "dewpoint_c": 3.9,
            "dewpoint_f": 39,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.1,
            "gust_kph": 22.7,
            "uv": 7
          },
          {
            "time_epoch": 1654081200,
            "time": "2022-06-01 13:00",
            "temp_c": 29.2,
            "temp_f": 84.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 12.8,
            "wind_kph": 20.5,
            "wind_degree": 224,
            "wind_dir": "SW",
            "pressure_mb": 1015,
            "pressure_in": 29.97,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 23,
            "cloud": 3,
            "feelslike_c": 27.4,
            "feelslike_f": 81.3,
            "windchill_c": 29.2,
            "windchill_f": 84.6,
            "heatindex_c": 27.4,
            "heatindex_f": 81.3,
            "dewpoint_c": 6.2,
            "dewpoint_f": 43.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.8,
            "gust_kph": 23.8,
            "uv": 7
          },
          {
            "time_epoch": 1654084800,
            "time": "2022-06-01 14:00",
            "temp_c": 27.3,
            "temp_f": 81.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 12.5,
            "wind_kph": 20.2,
            "wind_degree": 223,
            "wind_dir": "SW",
            "pressure_mb": 1014,
            "pressure_in": 29.94,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 22,
            "cloud": 2,
            "feelslike_c": 25.6,
            "feelslike_f": 78.1,
            "windchill_c": 27.3,
            "windchill_f": 81.1,
            "heatindex_c": 25.6,
            "heatindex_f": 78.1,
            "dewpoint_c": 3.5,
            "dewpoint_f": 38.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.3,
            "gust_kph": 23,
            "uv": 7
          },
          {
            "time_epoch": 1654088400,
            "time": "2022-06-01 15:00",
            "temp_c": 31.2,
            "temp_f": 88.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 13.4,
            "wind_kph": 21.6,
            "wind_degree": 223,
            "wind_dir": "SW",
            "pressure_mb": 1013,
            "pressure_in": 29.92,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 19,
            "cloud": 5,
            "feelslike_c": 28.9,
            "feelslike_f": 84,
            "windchill_c": 31.2,
            "windchill_f": 88.2,
            "heatindex_c": 28.9,
            "heatindex_f": 84,
            "dewpoint_c": 5.2,
            "dewpoint_f": 41.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15.4,
            "gust_kph": 24.8,
            "uv": 8
          },
          {
            "time_epoch": 1654092000,
            "time": "2022-06-01 16:00",
            "temp_c": 31.7,
            "temp_f": 89.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 14.1,
            "wind_kph": 22.7,
            "wind_degree": 223,
            "wind_dir": "SW",
            "pressure_mb": 1013,
            "pressure_in": 29.9,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 18,
            "cloud": 7,
            "feelslike_c": 29.5,
            "feelslike_f": 85.1,
            "windchill_c": 31.7,
            "windchill_f": 89.1,
            "heatindex_c": 29.5,
            "heatindex_f": 85.1,
            "dewpoint_c": 4.7,
            "dewpoint_f": 40.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.1,
            "gust_kph": 25.9,
            "uv": 8
          },
          {
            "time_epoch": 1654095600,
            "time": "2022-06-01 17:00",
            "temp_c": 31.6,
            "temp_f": 88.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 14.1,
            "wind_kph": 22.7,
            "wind_degree": 224,
            "wind_dir": "SW",
            "pressure_mb": 1012,
            "pressure_in": 29.89,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 18,
            "cloud": 7,
            "feelslike_c": 29.4,
            "feelslike_f": 84.9,
            "windchill_c": 31.6,
            "windchill_f": 88.9,
            "heatindex_c": 29.4,
            "heatindex_f": 84.9,
            "dewpoint_c": 4.2,
            "dewpoint_f": 39.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.1,
            "gust_kph": 25.9,
            "uv": 8
          },
          {
            "time_epoch": 1654099200,
            "time": "2022-06-01 18:00",
            "temp_c": 30.5,
            "temp_f": 86.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 15.2,
            "wind_kph": 24.5,
            "wind_degree": 238,
            "wind_dir": "WSW",
            "pressure_mb": 1012,
            "pressure_in": 29.88,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 19,
            "cloud": 7,
            "feelslike_c": 28.3,
            "feelslike_f": 82.9,
            "windchill_c": 30.5,
            "windchill_f": 86.9,
            "heatindex_c": 28.3,
            "heatindex_f": 82.9,
            "dewpoint_c": 3.9,
            "dewpoint_f": 39,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 17.4,
            "gust_kph": 28.1,
            "uv": 8
          },
          {
            "time_epoch": 1654102800,
            "time": "2022-06-01 19:00",
            "temp_c": 28.8,
            "temp_f": 83.8,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 13,
            "wind_kph": 20.9,
            "wind_degree": 243,
            "wind_dir": "WSW",
            "pressure_mb": 1012,
            "pressure_in": 29.88,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 20,
            "cloud": 9,
            "feelslike_c": 26.7,
            "feelslike_f": 80.1,
            "windchill_c": 28.8,
            "windchill_f": 83.8,
            "heatindex_c": 26.7,
            "heatindex_f": 80.1,
            "dewpoint_c": 3.9,
            "dewpoint_f": 39,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15,
            "gust_kph": 24.1,
            "uv": 7
          },
          {
            "time_epoch": 1654106400,
            "time": "2022-06-01 20:00",
            "temp_c": 26.7,
            "temp_f": 80.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 9.4,
            "wind_kph": 15.1,
            "wind_degree": 226,
            "wind_dir": "SW",
            "pressure_mb": 1012,
            "pressure_in": 29.89,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 23,
            "cloud": 8,
            "feelslike_c": 25.3,
            "feelslike_f": 77.5,
            "windchill_c": 26.7,
            "windchill_f": 80.1,
            "heatindex_c": 25.3,
            "heatindex_f": 77.5,
            "dewpoint_c": 4.2,
            "dewpoint_f": 39.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.9,
            "gust_kph": 22.3,
            "uv": 7
          },
          {
            "time_epoch": 1654110000,
            "time": "2022-06-01 21:00",
            "temp_c": 24.4,
            "temp_f": 75.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 13,
            "wind_kph": 20.9,
            "wind_degree": 238,
            "wind_dir": "WSW",
            "pressure_mb": 1013,
            "pressure_in": 29.91,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 34,
            "cloud": 5,
            "feelslike_c": 24.6,
            "feelslike_f": 76.3,
            "windchill_c": 24.4,
            "windchill_f": 75.9,
            "heatindex_c": 24.6,
            "heatindex_f": 76.3,
            "dewpoint_c": 7.5,
            "dewpoint_f": 45.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 20.1,
            "gust_kph": 32.4,
            "uv": 6
          },
          {
            "time_epoch": 1654113600,
            "time": "2022-06-01 22:00",
            "temp_c": 22.5,
            "temp_f": 72.5,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 11.9,
            "wind_kph": 19.1,
            "wind_degree": 238,
            "wind_dir": "WSW",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 41,
            "cloud": 2,
            "feelslike_c": 24.2,
            "feelslike_f": 75.6,
            "windchill_c": 22.5,
            "windchill_f": 72.5,
            "heatindex_c": 24.2,
            "heatindex_f": 75.6,
            "dewpoint_c": 8.7,
            "dewpoint_f": 47.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 20.6,
            "gust_kph": 33.1,
            "uv": 1
          },
          {
            "time_epoch": 1654117200,
            "time": "2022-06-01 23:00",
            "temp_c": 21.5,
            "temp_f": 70.7,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 10.7,
            "wind_kph": 17.3,
            "wind_degree": 242,
            "wind_dir": "WSW",
            "pressure_mb": 1014,
            "pressure_in": 29.96,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 45,
            "cloud": 2,
            "feelslike_c": 21.5,
            "feelslike_f": 70.7,
            "windchill_c": 21.5,
            "windchill_f": 70.7,
            "heatindex_c": 24.2,
            "heatindex_f": 75.6,
            "dewpoint_c": 9.2,
            "dewpoint_f": 48.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 18.3,
            "gust_kph": 29.5,
            "uv": 1
          }
        ]
      },
      {
        "date": "2022-06-02",
        "date_epoch": 1654128000,
        "day": {
          "maxtemp_c": 30.4,
          "maxtemp_f": 86.7,
          "mintemp_c": 17.4,
          "mintemp_f": 63.3,
          "avgtemp_c": 23.1,
          "avgtemp_f": 73.6,
          "maxwind_mph": 12.5,
          "maxwind_kph": 20.2,
          "totalprecip_mm": 0.4,
          "totalprecip_in": 0.02,
          "avgvis_km": 9.9,
          "avgvis_miles": 6,
          "avghumidity": 43,
          "daily_will_it_rain": 1,
          "daily_chance_of_rain": 85,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Patchy rain possible",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
            "code": 1063
          },
          "uv": 9
        },
        "astro": {
          "sunrise": "06:47 AM",
          "sunset": "09:40 PM",
          "moonrise": "08:46 AM",
          "moonset": "No moonset",
          "moon_phase": "Waxing Crescent",
          "moon_illumination": "16"
        },
        "hour": [
          {
            "time_epoch": 1654120800,
            "time": "2022-06-02 00:00",
            "temp_c": 20.5,
            "temp_f": 68.9,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 8.7,
            "wind_kph": 14,
            "wind_degree": 232,
            "wind_dir": "SW",
            "pressure_mb": 1015,
            "pressure_in": 29.96,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 49,
            "cloud": 4,
            "feelslike_c": 20.5,
            "feelslike_f": 68.9,
            "windchill_c": 20.5,
            "windchill_f": 68.9,
            "heatindex_c": 20.5,
            "heatindex_f": 68.9,
            "dewpoint_c": 9.5,
            "dewpoint_f": 49.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15.2,
            "gust_kph": 24.5,
            "uv": 1
          },
          {
            "time_epoch": 1654124400,
            "time": "2022-06-02 01:00",
            "temp_c": 19.8,
            "temp_f": 67.6,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 7.8,
            "wind_kph": 12.6,
            "wind_degree": 219,
            "wind_dir": "SW",
            "pressure_mb": 1015,
            "pressure_in": 29.96,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 53,
            "cloud": 3,
            "feelslike_c": 19.8,
            "feelslike_f": 67.6,
            "windchill_c": 19.8,
            "windchill_f": 67.6,
            "heatindex_c": 19.8,
            "heatindex_f": 67.6,
            "dewpoint_c": 9.8,
            "dewpoint_f": 49.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.4,
            "gust_kph": 21.6,
            "uv": 1
          },
          {
            "time_epoch": 1654128000,
            "time": "2022-06-02 02:00",
            "temp_c": 19.1,
            "temp_f": 66.4,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 7.6,
            "wind_kph": 12.2,
            "wind_degree": 217,
            "wind_dir": "SW",
            "pressure_mb": 1015,
            "pressure_in": 29.96,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 56,
            "cloud": 2,
            "feelslike_c": 19.1,
            "feelslike_f": 66.4,
            "windchill_c": 19.1,
            "windchill_f": 66.4,
            "heatindex_c": 19.1,
            "heatindex_f": 66.4,
            "dewpoint_c": 10.2,
            "dewpoint_f": 50.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13,
            "gust_kph": 20.9,
            "uv": 1
          },
          {
            "time_epoch": 1654131600,
            "time": "2022-06-02 03:00",
            "temp_c": 18.5,
            "temp_f": 65.3,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 7.4,
            "wind_kph": 11.9,
            "wind_degree": 222,
            "wind_dir": "SW",
            "pressure_mb": 1015,
            "pressure_in": 29.96,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 59,
            "cloud": 3,
            "feelslike_c": 18.5,
            "feelslike_f": 65.3,
            "windchill_c": 18.5,
            "windchill_f": 65.3,
            "heatindex_c": 18.5,
            "heatindex_f": 65.3,
            "dewpoint_c": 10.4,
            "dewpoint_f": 50.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.8,
            "gust_kph": 20.5,
            "uv": 1
          },
          {
            "time_epoch": 1654135200,
            "time": "2022-06-02 04:00",
            "temp_c": 18.1,
            "temp_f": 64.6,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 228,
            "wind_dir": "SW",
            "pressure_mb": 1015,
            "pressure_in": 29.96,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 61,
            "cloud": 3,
            "feelslike_c": 18.1,
            "feelslike_f": 64.6,
            "windchill_c": 18.1,
            "windchill_f": 64.6,
            "heatindex_c": 18.1,
            "heatindex_f": 64.6,
            "dewpoint_c": 10.5,
            "dewpoint_f": 50.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.2,
            "gust_kph": 18,
            "uv": 1
          },
          {
            "time_epoch": 1654138800,
            "time": "2022-06-02 05:00",
            "temp_c": 17.7,
            "temp_f": 63.9,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 5.4,
            "wind_kph": 8.6,
            "wind_degree": 232,
            "wind_dir": "SW",
            "pressure_mb": 1015,
            "pressure_in": 29.96,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 63,
            "cloud": 5,
            "feelslike_c": 17.7,
            "feelslike_f": 63.9,
            "windchill_c": 17.7,
            "windchill_f": 63.9,
            "heatindex_c": 17.7,
            "heatindex_f": 63.9,
            "dewpoint_c": 10.5,
            "dewpoint_f": 50.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.4,
            "gust_kph": 15.1,
            "uv": 1
          },
          {
            "time_epoch": 1654142400,
            "time": "2022-06-02 06:00",
            "temp_c": 17.4,
            "temp_f": 63.3,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 229,
            "wind_dir": "SW",
            "pressure_mb": 1015,
            "pressure_in": 29.98,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 64,
            "cloud": 6,
            "feelslike_c": 17.4,
            "feelslike_f": 63.3,
            "windchill_c": 17.4,
            "windchill_f": 63.3,
            "heatindex_c": 17.4,
            "heatindex_f": 63.3,
            "dewpoint_c": 10.5,
            "dewpoint_f": 50.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.4,
            "gust_kph": 11.9,
            "uv": 1
          },
          {
            "time_epoch": 1654146000,
            "time": "2022-06-02 07:00",
            "temp_c": 18.3,
            "temp_f": 64.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.8,
            "wind_kph": 6.1,
            "wind_degree": 227,
            "wind_dir": "SW",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 60,
            "cloud": 7,
            "feelslike_c": 18.3,
            "feelslike_f": 64.9,
            "windchill_c": 18.3,
            "windchill_f": 64.9,
            "heatindex_c": 18.3,
            "heatindex_f": 64.9,
            "dewpoint_c": 10.5,
            "dewpoint_f": 50.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.6,
            "gust_kph": 9,
            "uv": 5
          },
          {
            "time_epoch": 1654149600,
            "time": "2022-06-02 08:00",
            "temp_c": 19.7,
            "temp_f": 67.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 4.7,
            "wind_kph": 7.6,
            "wind_degree": 225,
            "wind_dir": "SW",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 56,
            "cloud": 7,
            "feelslike_c": 19.7,
            "feelslike_f": 67.5,
            "windchill_c": 19.7,
            "windchill_f": 67.5,
            "heatindex_c": 19.7,
            "heatindex_f": 67.5,
            "dewpoint_c": 10.7,
            "dewpoint_f": 51.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.6,
            "gust_kph": 9,
            "uv": 5
          },
          {
            "time_epoch": 1654153200,
            "time": "2022-06-02 09:00",
            "temp_c": 21,
            "temp_f": 69.8,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 5.8,
            "wind_kph": 9.4,
            "wind_degree": 219,
            "wind_dir": "SW",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 52,
            "cloud": 6,
            "feelslike_c": 21,
            "feelslike_f": 69.8,
            "windchill_c": 21,
            "windchill_f": 69.8,
            "heatindex_c": 21,
            "heatindex_f": 69.8,
            "dewpoint_c": 10.8,
            "dewpoint_f": 51.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.7,
            "gust_kph": 10.8,
            "uv": 6
          },
          {
            "time_epoch": 1654156800,
            "time": "2022-06-02 10:00",
            "temp_c": 22.2,
            "temp_f": 72,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 6,
            "wind_kph": 9.7,
            "wind_degree": 211,
            "wind_dir": "SSW",
            "pressure_mb": 1015,
            "pressure_in": 29.98,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 48,
            "cloud": 5,
            "feelslike_c": 24.4,
            "feelslike_f": 75.9,
            "windchill_c": 22.2,
            "windchill_f": 72,
            "heatindex_c": 24.4,
            "heatindex_f": 75.9,
            "dewpoint_c": 10.7,
            "dewpoint_f": 51.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.9,
            "gust_kph": 11.2,
            "uv": 6
          },
          {
            "time_epoch": 1654160400,
            "time": "2022-06-02 11:00",
            "temp_c": 24,
            "temp_f": 75.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 7.2,
            "wind_kph": 11.5,
            "wind_degree": 208,
            "wind_dir": "SSW",
            "pressure_mb": 1015,
            "pressure_in": 29.98,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 42,
            "cloud": 10,
            "feelslike_c": 24.9,
            "feelslike_f": 76.8,
            "windchill_c": 24,
            "windchill_f": 75.2,
            "heatindex_c": 24.9,
            "heatindex_f": 76.8,
            "dewpoint_c": 10.3,
            "dewpoint_f": 50.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.3,
            "gust_kph": 13.3,
            "uv": 6
          },
          {
            "time_epoch": 1654164000,
            "time": "2022-06-02 12:00",
            "temp_c": 25,
            "temp_f": 77,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 9.2,
            "wind_kph": 14.8,
            "wind_degree": 212,
            "wind_dir": "SSW",
            "pressure_mb": 1015,
            "pressure_in": 29.96,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 37,
            "cloud": 14,
            "feelslike_c": 25.2,
            "feelslike_f": 77.4,
            "windchill_c": 25,
            "windchill_f": 77,
            "heatindex_c": 25.2,
            "heatindex_f": 77.4,
            "dewpoint_c": 9.1,
            "dewpoint_f": 48.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.5,
            "gust_kph": 16.9,
            "uv": 7
          },
          {
            "time_epoch": 1654167600,
            "time": "2022-06-02 13:00",
            "temp_c": 27,
            "temp_f": 80.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 9.8,
            "wind_kph": 15.8,
            "wind_degree": 215,
            "wind_dir": "SW",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 33,
            "cloud": 11,
            "feelslike_c": 26.4,
            "feelslike_f": 79.5,
            "windchill_c": 27,
            "windchill_f": 80.6,
            "heatindex_c": 26.4,
            "heatindex_f": 79.5,
            "dewpoint_c": 9.3,
            "dewpoint_f": 48.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.4,
            "gust_kph": 18.4,
            "uv": 7
          },
          {
            "time_epoch": 1654171200,
            "time": "2022-06-02 14:00",
            "temp_c": 29.3,
            "temp_f": 84.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.1,
            "wind_kph": 13,
            "wind_degree": 222,
            "wind_dir": "SW",
            "pressure_mb": 1013,
            "pressure_in": 29.92,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 31,
            "cloud": 9,
            "feelslike_c": 28.2,
            "feelslike_f": 82.8,
            "windchill_c": 29.3,
            "windchill_f": 84.7,
            "heatindex_c": 28.2,
            "heatindex_f": 82.8,
            "dewpoint_c": 10.2,
            "dewpoint_f": 50.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.2,
            "gust_kph": 14.8,
            "uv": 7
          },
          {
            "time_epoch": 1654174800,
            "time": "2022-06-02 15:00",
            "temp_c": 30.4,
            "temp_f": 86.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.7,
            "wind_kph": 14,
            "wind_degree": 229,
            "wind_dir": "SW",
            "pressure_mb": 1013,
            "pressure_in": 29.91,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 27,
            "cloud": 4,
            "feelslike_c": 28.9,
            "feelslike_f": 84,
            "windchill_c": 30.4,
            "windchill_f": 86.7,
            "heatindex_c": 28.9,
            "heatindex_f": 84,
            "dewpoint_c": 9.1,
            "dewpoint_f": 48.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.1,
            "gust_kph": 16.2,
            "uv": 8
          },
          {
            "time_epoch": 1654178400,
            "time": "2022-06-02 16:00",
            "temp_c": 28.6,
            "temp_f": 83.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 9.8,
            "wind_kph": 15.8,
            "wind_degree": 228,
            "wind_dir": "SW",
            "pressure_mb": 1012,
            "pressure_in": 29.89,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 23,
            "cloud": 17,
            "feelslike_c": 26.8,
            "feelslike_f": 80.2,
            "windchill_c": 28.6,
            "windchill_f": 83.5,
            "heatindex_c": 26.8,
            "heatindex_f": 80.2,
            "dewpoint_c": 5.2,
            "dewpoint_f": 41.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.4,
            "gust_kph": 18.4,
            "uv": 7
          },
          {
            "time_epoch": 1654182000,
            "time": "2022-06-02 17:00",
            "temp_c": 29.2,
            "temp_f": 84.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 10.5,
            "wind_kph": 16.9,
            "wind_degree": 226,
            "wind_dir": "SW",
            "pressure_mb": 1012,
            "pressure_in": 29.88,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 21,
            "cloud": 14,
            "feelslike_c": 27.1,
            "feelslike_f": 80.8,
            "windchill_c": 29.2,
            "windchill_f": 84.6,
            "heatindex_c": 27.1,
            "heatindex_f": 80.8,
            "dewpoint_c": 4.5,
            "dewpoint_f": 40.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.1,
            "gust_kph": 19.4,
            "uv": 7
          },
          {
            "time_epoch": 1654185600,
            "time": "2022-06-02 18:00",
            "temp_c": 27.9,
            "temp_f": 82.2,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 11.4,
            "wind_kph": 18.4,
            "wind_degree": 224,
            "wind_dir": "SW",
            "pressure_mb": 1012,
            "pressure_in": 29.87,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 22,
            "cloud": 48,
            "feelslike_c": 26.1,
            "feelslike_f": 79,
            "windchill_c": 27.9,
            "windchill_f": 82.2,
            "heatindex_c": 26.1,
            "heatindex_f": 79,
            "dewpoint_c": 4.3,
            "dewpoint_f": 39.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.4,
            "gust_kph": 21.6,
            "uv": 7
          },
          {
            "time_epoch": 1654189200,
            "time": "2022-06-02 19:00",
            "temp_c": 25.6,
            "temp_f": 78.1,
            "is_day": 1,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 12.5,
            "wind_kph": 20.2,
            "wind_degree": 231,
            "wind_dir": "SW",
            "pressure_mb": 1012,
            "pressure_in": 29.88,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 30,
            "cloud": 65,
            "feelslike_c": 25.1,
            "feelslike_f": 77.2,
            "windchill_c": 25.6,
            "windchill_f": 78.1,
            "heatindex_c": 25.1,
            "heatindex_f": 77.2,
            "dewpoint_c": 6.5,
            "dewpoint_f": 43.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 17.7,
            "gust_kph": 28.4,
            "uv": 6
          },
          {
            "time_epoch": 1654192800,
            "time": "2022-06-02 20:00",
            "temp_c": 24.5,
            "temp_f": 76.1,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 6.9,
            "wind_kph": 11.2,
            "wind_degree": 212,
            "wind_dir": "SSW",
            "pressure_mb": 1012,
            "pressure_in": 29.89,
            "precip_mm": 0.2,
            "precip_in": 0.01,
            "humidity": 34,
            "cloud": 73,
            "feelslike_c": 24.7,
            "feelslike_f": 76.5,
            "windchill_c": 24.5,
            "windchill_f": 76.1,
            "heatindex_c": 24.7,
            "heatindex_f": 76.5,
            "dewpoint_c": 7.5,
            "dewpoint_f": 45.5,
            "will_it_rain": 1,
            "chance_of_rain": 76,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9,
            "vis_miles": 5,
            "gust_mph": 11,
            "gust_kph": 17.6,
            "uv": 5
          },
          {
            "time_epoch": 1654196400,
            "time": "2022-06-02 21:00",
            "temp_c": 24.4,
            "temp_f": 75.9,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 4.5,
            "wind_kph": 7.2,
            "wind_degree": 155,
            "wind_dir": "SSE",
            "pressure_mb": 1012,
            "pressure_in": 29.89,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 33,
            "cloud": 60,
            "feelslike_c": 24.6,
            "feelslike_f": 76.3,
            "windchill_c": 24.4,
            "windchill_f": 75.9,
            "heatindex_c": 24.6,
            "heatindex_f": 76.3,
            "dewpoint_c": 7.1,
            "dewpoint_f": 44.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.2,
            "gust_kph": 11.5,
            "uv": 6
          },
          {
            "time_epoch": 1654200000,
            "time": "2022-06-02 22:00",
            "temp_c": 23.8,
            "temp_f": 74.8,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 5.4,
            "wind_kph": 8.6,
            "wind_degree": 148,
            "wind_dir": "SSE",
            "pressure_mb": 1013,
            "pressure_in": 29.91,
            "precip_mm": 0.2,
            "precip_in": 0.01,
            "humidity": 36,
            "cloud": 86,
            "feelslike_c": 24.4,
            "feelslike_f": 75.9,
            "windchill_c": 23.8,
            "windchill_f": 74.8,
            "heatindex_c": 24.4,
            "heatindex_f": 75.9,
            "dewpoint_c": 7.7,
            "dewpoint_f": 45.9,
            "will_it_rain": 1,
            "chance_of_rain": 85,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9,
            "vis_miles": 5,
            "gust_mph": 8.5,
            "gust_kph": 13.7,
            "uv": 1
          },
          {
            "time_epoch": 1654203600,
            "time": "2022-06-02 23:00",
            "temp_c": 23.2,
            "temp_f": 73.8,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 6,
            "wind_kph": 9.7,
            "wind_degree": 163,
            "wind_dir": "SSE",
            "pressure_mb": 1013,
            "pressure_in": 29.92,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 38,
            "cloud": 48,
            "feelslike_c": 24.3,
            "feelslike_f": 75.7,
            "windchill_c": 23.2,
            "windchill_f": 73.8,
            "heatindex_c": 24.3,
            "heatindex_f": 75.7,
            "dewpoint_c": 8.3,
            "dewpoint_f": 46.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.4,
            "gust_kph": 15.1,
            "uv": 1
          }
        ]
      }
    ]
  }
}
export default mock;